### ISSUE TITLE
Dont work use global interface

### ISSUE THREAD

**Issue by FelipeRodrigues21** [OpenFeign/feign-annotation-error-decoder#10]
Hi, I'm using the annotation and I had a big problem, when I create a unique interface and try to extend it in other interfaces does not work.

**Comment by saintf** [comment]
Let me give that a try (basically... The annotations aren't necessarily
inherited).

I can try to make the change to support inheritance.

**Comment by FelipeRodrigues21** [comment]
Ok, thanks.

**Comment by saintf** [comment]
@FelipeRodrigues21 can you check the changes under https://github.com/saintf/feign-annotation-error-decoder/commit/2768e45d8c0de9927d8a42f65a46a07f57ad229f and see if they make sense to you/provide any feedback (changes/etc).

It "supports" inheritance (although annotation inheritance for interfaces isn't supported by java - but I can completely get if you want to have a base interface that defines the usual 4**'s and makes the exceptions fairly unified accross).

If that looks good, I'll look at pulling into the new version (which also upgrades us to 10.** series of feign)

**Comment by saintf** [comment]
@FelipeRodrigues21 actually - would be better if you can review the PR (https://github.com/OpenFeign/feign-annotation-error-decoder/pull/17). If all good, then I can merge and look to release.

**Comment by saintf** [comment]
merged and released. You should find from 1.1.1 the annotation is "inherited". Details in the documentation. enjoy!
