### ISSUE TITLE
Use own ExceptionGenerator

### ISSUE THREAD

**Issue by MariusKl** [OpenFeign/feign-annotation-error-decoder#22]
Hi,

I would like to use my own ExceptionGenerator to be free to add another field (requestUrl) to my exception. Could you adapt the AnnotationErrorDecoder to be able to pass an ExceptionGeneratorBuilder to this class? 

I thought about adding a new method

` public Builder withExceptionGeneratorBuilder(ExceptionGenerator.Builder exceptionGenerator) {
      this.exceptionGenerator = exceptionGenerator;
      return this;
    }`

to the AnnotationErrorDecoder, but due to the current design this would lead to a lot of changes in the ExceptionGenerator and ExceptionGeneratorBuilder classes and its design.

**Comment by saintf** [comment]
Rather than doing that (Which is basically taking a ton of the heart away) would it be better if instead we allowed you to capture the request object provided by Feign?

You could hence perhaps take the request as a parameter and then use its internals to capture requestUrl/headers/etc - thoughts?

**Comment by StefanFellinger** [comment]
It's an idea. Would be fine for us. Mabe you can provide a single DTO Object that holds request, response and the body or the method that resolves it. Then Exception Constructors need less parameters and the DTO can be extended when things change...

**Comment by saintf** [comment]
Take a look at https://github.com/OpenFeign/feign-annotation-error-decoder/issues/18 - the idea is that it would then return a standard Feign Request object (look at https://github.com/OpenFeign/feign/blob/master/core/src/main/java/feign/Request.java) which you can then use to get resolved URI/Headers/etc if you want.

If that looks good, let's close this ticket out and upvote that one. Are you ok to give it a try at making the changes and I can review afterwards?

**Comment by MariusKl** [comment]
Thank you for adding this in #18
