### ISSUE TITLE
Gradle dependency

### ISSUE THREAD

**Issue by srikumarcs** [OpenFeign/feign-annotation-error-decoder#3]
Hi,

This is something quite useful for us and we are looking for a more Annotation based handling of Error Codes. Is there a Gradle dependency for this that we could use? We are using Feign with Hystrix, plugged in using OkHttp client. 

Regards,
Sri

**Comment by saintf** [comment]
Hi Sri -
I need to get this released and into maven central and then you should be able to use it (apologies it's taken me so long!)

**Comment by scoquelin** [comment]
@srikumarcs @saintf +1 here to get this on maven central let me know if/how I can help out for this !

**Comment by saintf** [comment]
@srikumarcs @scoquelin Sorry guys - took a while - and still taking - but - almost there!

I had to update credentials and get a few bits and pieces going in the orchestration for releases - but... I seem to finally have all the appropriate rights and such. A release version of this is sitting in bintray - waiting to be manually reviewed by one of the moderators, and as soon as they approve we should be able to push to maven central. When that's done - I'll ping over the coordinates.

Sorry and thanks for your patience!

**Comment by saintf** [comment]
@srikumarcs @scoquelin released!
https://search.maven.org/#artifactdetails%7Cio.github.openfeign%7Cfeign-annotation-error-decoder%7C1.0.3%7Cjar

Try it out and enjoy!
